# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_permissions"
version = "0.1.0"
edition = "2018"
description = "provides permissions implementation for deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
atty = "0.2.14"
deno_colors = { version = "0.1.0", path = "../colors" }
deno_core = { version = "0.58.0", path = "../../core" }
serde = { version = "1.0.116", features = ["derive"] }
deno_flags = { version = "0.1.0", path = "../flags" }
deno_fs = { version = "0.1.0", path = "../fs" }
deno_fetch = { version = "0.1.0", path = "../../op_crates/fetch" }
log = "0.4.11"
termcolor = "1.1.0"

[dev-dependencies]
lazy_static = "1.4.0"
