# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_flags"
version = "0.1.0"
edition = "2018"
description = "provides flags implementation for deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.59.0", path = "../../core" }
deno_version = { version = "0.1.0", path = "../version" }
serde = { version = "1.0.116", features = ["derive"] }
clap = "2.33.3"
log = "0.4.11"
lazy_static = "1.4.0"
tempfile = "3.1.0"
