# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_broadcast_channel"
<<<<<<< HEAD
version = "0.124.0"
=======
version = "0.125.0"
>>>>>>> aa23ccd1a (1.39.3 (#21913))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of BroadcastChannel API for Deno"

[lib]
path = "lib.rs"

[dependencies]
async-trait.workspace = true
deno_core.workspace = true
tokio.workspace = true
uuid.workspace = true
