# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_console"
<<<<<<< HEAD
version = "0.133.0"
=======
version = "0.134.0"
>>>>>>> b003ecec6 (1.40.1 (#22103))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of Console API for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
