# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_css"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "CSSOM API implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
cssparser = "0.29.2"
deno_core = { version = "0.127.0", path = "../../core" }
parcel_css = { version = "1.0.0-alpha.21", git = "https://github.com/parcel-bundler/parcel-css", rev = "7c1db82e266fc0df0343c1c39098ee73f5174a24" }
serde = "1"