sudo: required

language: c++

services:
  - docker

env:
  global:
    - CACHE_DIR=$HOME/.cache/docker
    - CACHE_FILE_BUILDER=$CACHE_DIR/docker-builder.tar.gz
cache:
  directories:
    - $CACHE_DIR

before_install:
  - docker version
  - if [ -f ${CACHE_FILE_BUILDER} ]; then gunzip -c ${CACHE_FILE_BUILDER} | docker load; fi
  - docker images
  - docker build --cache-from deno-builder:latest -t deno-builder:latest -f Dockerfile_builder .

script:
  - docker run -it --rm -v ${PWD}:/root/go/src/github.com/ry/deno deno-builder make lint
  - docker run -it --rm -v ${PWD}:/root/go/src/github.com/ry/deno deno-builder make test
  - if [ ! -d ${CACHE_DIR} ]; then mkdir -p ${CACHE_DIR}; fi
  - if [ ! -f ${CACHE_FILE_BUILDER} ]; then docker save deno-builder | gzip > ${CACHE_FILE_BUILDER}; fi