sudo: required

language: c++

services:
  - docker
cache:
  ccache: true
  directories:
   - .cache/
   - node_modules/
   - $V8WORKER2_OUT_PATH

before_install:
  - docker build -t deno-builder -f Dockerfile_builder .

script:
  - docker run -it --rm -v ${PWD}:/root/go/src/github.com/ry/deno deno-builder

