steps:

- checkout: self
  submodules: true

- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
    export PATH=$PATH:$HOME/.cargo/bin
  displayName: 'Install rustc'

- script: python ./tools/setup.py
  displayName: 'setup.py'

- script: python ./tools/build.py
  displayName: 'build.py'
