[workspace]
members = [
  "cli",
  "core",
  "test_plugin",
  "test_util",
  "op_crates/web",
]
exclude = [
  "std/hash/_wasm"
]

[profile.release]
opt-level = 2
debug = 2

[profile.bench]
opt-level = 2
debug = 2
