# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.
[workspace]
members = [
  "cli",
  "core",
  "runtime",
  "serde_v8",
  "test_plugin",
  "test_util",
  "extensions/crypto",
  "extensions/fetch",
  "extensions/timers",
  "extensions/url",
  "extensions/web",
  "extensions/webgpu",
  "extensions/webidl",
  "extensions/websocket",
]
exclude = ["std/hash/_wasm"]
