# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[workspace]
members = [
  "cli",
  "core",
  "test_plugin",
  "test_util",
  "op_crates/fetch",
  "op_crates/web",
  "crates/colors",
  "crates/flags",
  "crates/fs",
  "crates/permissions",
  "crates/version",
]
exclude = [
  "std/hash/_wasm"
]


[profile.release]
codegen-units = 1
lto = true
opt-level = 'z' # Optimize for size

[profile.bench]
codegen-units = 1
lto = true
opt-level = 'z' # Optimize for size
