# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.
[workspace]
members = [
  "cli",
  "core",
  "runtime",
  "serde_v8",
  "test_plugin",
  "test_util",
  "op_crates/crypto",
  "op_crates/fetch",
  "op_crates/timers",
  "op_crates/url",
  "op_crates/web",
  "op_crates/webgpu",
  "op_crates/webidl",
  "op_crates/websocket",
]
exclude = ["std/hash/_wasm"]
