[workspace]
members = [
  "bundle_util",
  "cli",
  "tools/hyper_hello",
  "cli_snapshots",
  "core",
  "deno_typescript",
  "dispatch_json",
  "dispatch_json/bundle",
  "ops/fs",
  "ops/fs/bundle",
]
