[package]
name = "test_plugin"
version = "0.0.1"
authors = ["the deno authors"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.4"
deno_core = { path = "../core", features = ["dispatch_json"] }
deno = { path = "../cli" }
serde_json = "1.0.44"
serde = { version = "1.0.102", features = ["derive"] }
serde_derive = "1.0.102" 
