# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_url"
version = "0.89.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "URL API implementation for Deno"

[features]
include_js_files_for_snapshotting = ["deno_core/include_js_files_for_snapshotting"]

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
serde.workspace = true
serde_repr.workspace = true
urlpattern = "0.2.0"

[dev-dependencies]
deno_bench_util.workspace = true
deno_webidl.workspace = true

[[bench]]
name = "url_ops"
harness = false
