# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_url"
<<<<<<< HEAD
version = "0.146.0"
=======
version = "0.147.0"
>>>>>>> 7cb23c5e3 (1.42.4 (#23390))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "URL API implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
serde.workspace = true
urlpattern = "0.2.0"

[dev-dependencies]
deno_bench_util.workspace = true
deno_console.workspace = true
deno_webidl.workspace = true

[[bench]]
name = "url_ops"
harness = false
