# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_url"
<<<<<<< HEAD
version = "0.133.0"
=======
version = "0.134.0"
>>>>>>> b003ecec6 (1.40.1 (#22103))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "URL API implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
serde.workspace = true
urlpattern = "0.2.0"

[dev-dependencies]
deno_bench_util.workspace = true
deno_console.workspace = true
deno_webidl.workspace = true

[[bench]]
name = "url_ops"
harness = false
