# This is an imagined crate directory structure for Deno ops.
# Same as op_hello but done with JS and not TS.

[package]
name = "op_hello_js"
version = "0.1.0"
authors = ["Ryan Dahl <ry@tinyclouds.org>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
deno = { path = "../core", version = "0.19.0" }

[[example]]
name = "op_hello_example"
path = "examples/hello.rs"

# tokio is only used for op_hello_example
[dev_dependencies]
futures = "0.1.29"
tokio = "0.1.18"
