# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_fs"
<<<<<<< HEAD
version = "0.10.0"
=======
version = "0.11.0"
>>>>>>> d5f52ef7a (1.33.1 (#18895))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Ops for interacting with the file system"

[lib]
path = "lib.rs"

[dependencies]
async-trait.workspace = true
deno_core.workspace = true
deno_io.workspace = true
filetime = "0.2.16"
fs3 = "0.5.0"
libc.workspace = true
log.workspace = true
rand.workspace = true
serde.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["winbase"] }
