[package]
name = "deno_typescript"
version = "0.49.0"
license = "MIT"
description = "To compile TypeScript to a snapshot during build.rs"
repository = "https://github.com/denoland/deno"
authors = ["the Deno authors"]
edition = "2018"

exclude = [
  "typescript/tests/*",
  "typescript/src/*",
  "typescript/scripts/*",
  "typescript/doc/*",
  "typescript/lib/*/*.json",
]

[lib]
path = "lib.rs"

[dependencies]
bytecount = "0.6.0"
deno_core = { path = "../core", version = "0.49.0" }
ring = "0.16.15"
regex = "1.3.9"
serde_json = "1.0.56"
serde = { version = "1.0.114", features = ["derive"] }
sourcemap = "6.0.0"

[dev-dependencies]
tempfile = "3.1.0"
