# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webserial"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Implementation of Web Serial API for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.118.0", path = "../../core" }
serde = { version = "1.0.129", features = ["derive"] }
# needed for a type
serialport = "4.0.1"
tokio = { version = "1.10.1", features = ["full"] }
tokio-serial = "5.4.1"
