blank_issues_enabled: true
contact_links:
  - name: 💡 Community Feature Requets
    url: https://discord.com/deno
    about: Suggest an idea, feature or enhancement in the Ideas Discord forum.
  - name: 💬 Ask a Question, Discuss and learn how others are using Deno
    url: https://discord.com/deno
    about: Join our Discord server for questions, support requests, or just to chat.
