name: 🚀 Deno land Feature request
description: Suggest an idea, feature or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an idea. It helps make Deno better.

        This is only for CLI / Deno land items. For community projects, please use the Ideas forum in [Discord](https://discord.com/deno).
  - type: textarea
    attributes:
      label: What is the problem this feature would solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the feature you are proposing to solve the problem?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered?
