# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_websocket"
<<<<<<< HEAD
version = "0.128.0"
=======
version = "0.129.0"
>>>>>>> 118be11e8 (fix(runtime): snapshot options op missing during snapshot (#21235))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of WebSocket API for Deno"

[lib]
path = "lib.rs"

[dependencies]
bytes.workspace = true
deno_core.workspace = true
deno_net.workspace = true
deno_tls.workspace = true
fastwebsockets = { workspace = true, features = ["upgrade", "unstable-split"] }
h2.workspace = true
http.workspace = true
hyper = { workspace = true, features = ["backports"] }
once_cell.workspace = true
rustls-tokio-stream.workspace = true
serde.workspace = true
tokio.workspace = true
