# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_websocket"
<<<<<<< HEAD
version = "0.157.0"
=======
version = "0.158.0"
>>>>>>> 7df3d5aee (1.43.6 (#23932))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of WebSocket API for Deno"

[lib]
path = "lib.rs"

[dependencies]
bytes.workspace = true
deno_core.workspace = true
deno_net.workspace = true
deno_tls.workspace = true
fastwebsockets.workspace = true
h2.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
once_cell.workspace = true
rustls-tokio-stream.workspace = true
serde.workspace = true
tokio.workspace = true
