# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_fetch"
<<<<<<< HEAD
version = "0.124.0"
=======
version = "0.125.0"
>>>>>>> d5f52ef7a (1.33.1 (#18895))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Fetch API implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
bytes.workspace = true
data-url.workspace = true
deno_core.workspace = true
deno_tls.workspace = true
dyn-clone = "1"
http.workspace = true
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-stream = "0.1.8"
tokio-util = { workspace = true, features = ["io"] }
