# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_fetch"
version = "0.132.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Fetch API implementation for Deno"

[lib]
path = "lib.rs"

[features]
# Enable to exclude JS sources from the binary (e.g. if they are already snapshotted).
exclude_js_sources = []
# Enable to override `exclude_js_sources` (e.g. for snapshot creation in `build.rs`).
force_include_js_sources = []

[dependencies]
bytes.workspace = true
data-url.workspace = true
deno_core.workspace = true
deno_tls.workspace = true
dyn-clone = "1"
http.workspace = true
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-stream = "0.1.8"
tokio-util = { workspace = true, features = ["io"] }
