# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_fetch"
<<<<<<< HEAD
version = "0.168.0"
=======
version = "0.169.0"
>>>>>>> 04c0a4cbf (1.42.2 (#23314))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Fetch API implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
bytes.workspace = true
data-url.workspace = true
deno_core.workspace = true
deno_tls.workspace = true
dyn-clone = "1"
http_v02.workspace = true
pin-project.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util = { workspace = true, features = ["io"] }
