[package]
name = "hyper_hello"
version = "0.0.1"
edition = "2018"

[dependencies]
hyper = "0.13.6"
tokio = { version = "0.2.21", features = ["rt-core", "tcp", "udp", "uds", "process", "fs", "blocking", "sync", "io-std", "macros", "time"] }

[[bin]]
name = "hyper_hello"
path = "hyper_hello.rs"
