# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_flash"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Fast HTTP/1 server implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { path = "../../core", version = "0.144.0" }
# For HTTP/2 and websocket upgrades
deno_websocket = { version = "0.67.0", path = "../websocket" }
http = "0.2.6"
httparse = "1.7"
hyper = { version = "0.14.18", features = ["server", "stream", "http1", "http2", "runtime"] }
mio = { version = "0.8", features = ["os-poll", "net"] }
rustls = { version = "0.20" }
rustls-pemfile = { version = "0.2.1" }
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.19", features = ["full"] }
