# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_sqlite"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "SQLite for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.142.0", path = "../../core" }
fallible-iterator = "0.2.0"
rusqlite = { version = "0.27.0", features = ["unlock_notify", "bundled"] }
serde = { version = "1.0.136", features = ["derive"] }
