# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_napi"
version = "0.0.1"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "NAPI implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.153.0", path = "../../core" }
# For permissions
deno_ffi = { version = "0.58.0", path = "../ffi" }
libloading = { version = "0.7" }
