# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_napi"
<<<<<<< HEAD
version = "0.38.0"
=======
version = "0.39.0"
>>>>>>> ef24d1a0b (1.34.3 (#19525))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "NAPI implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
libloading = { version = "0.7" }
