# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_napi"
<<<<<<< HEAD
version = "0.74.0"
=======
version = "0.75.0"
>>>>>>> 04c0a4cbf (1.42.2 (#23314))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "NAPI implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
libloading = { version = "0.7" }
