# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.
[package]
name = "polloi"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "An I/O poller for the hoi polloi"

[lib]
path = "lib.rs"

[dependencies]
c = { version = "0.2", package = "libc" }
mio = { version = "0.8", features = ["os-poll", "net"] }
