# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_crypto"
version = "0.64.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Web Cryptography API implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
aes = "0.8.1"
# TODO(@littledivy): Move to stable release
# https://github.com/RustCrypto/AEADs/issues/411
aes-gcm = "0.10.0-pre"
aes-kw = { version = "0.2.1", features = ["alloc"] }
base64 = "0.13.0"
block-modes = "0.8.1"
cbc = { version = "0.1.2", features = ["alloc"] }
ctr = "0.9.1"
elliptic-curve = { version = "0.11.12", features = ["std", "pem"] }
deno_core = { version = "0.132.0", path = "../../core" }
deno_web = { version = "0.81.0", path = "../web" }
num-traits = "0.2.14"
once_cell = "1.10.0"
p256 = { version = "0.10.1", features = ["ecdh"] }
p384 = "0.9.0"
rand = "0.8.4"
ring = { version = "0.16.20", features = ["std"] }
rsa = { version = "0.6.1", default-features = false, features = ["std"] }
serde = { version = "1.0.129", features = ["derive"] }
serde_bytes = "0.11"
sha-1 = "0.10.0"
sha2 = "0.10.2"
spki = "0.5.2"
tokio = { version = "1.17", features = ["full"] }
uuid = { version = "0.8.2", features = ["v4"] }
