[package]
name = "deno-mail"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
repository = "https://github.com/denoland/deno"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
digest = "0.9.0"
wasm-bindgen = { version = "0.2.68", features = ["serde-serialize"] }
js-sys = "0.3.45"
mailparse = "0.13.0"
serde = "1.0.116"
serde_derive = "1.0.116"

[profile.release]
lto = true
opt-level = 3

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-mutable-globals"]
