# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "napi_sym"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "proc macro for writing N-API symbols"

[lib]
path = "./lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syn = { version = "1", features = ["full", "extra-traits"] }
