# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_io"
<<<<<<< HEAD
version = "0.21.0"
=======
version = "0.22.0"
>>>>>>> 60fe8aa53 (1.35.2 (#19885))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "IO primitives for Deno extensions"

[lib]
path = "lib.rs"

[dependencies]
async-trait.workspace = true
deno_core.workspace = true
filetime.workspace = true
fs3.workspace = true
once_cell.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["winbase", "processenv"] }
