# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_net"
version = "0.1.0"
edition = "2018"
description = "Networking for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.91.0", path = "../../core" }
tokio = { version = "1.7.1", features = ["full"] }
