# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_sys"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Various system related functionality for deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.99.0", path = "../../core" }
deno_crypto = { version = "0.31.0", path = "../crypto" }
deno_net = { version = "0.8.0", path = "../net" }
filetime = "0.2.15"
fs3 = "0.5.0"
lazy_static = "1.4.0"
libc = "0.2.101"
log = "0.4.14"
notify = "=5.0.0-pre.12"
serde = { version = "1.0.129", features = ["derive"] }
sys-info = "0.9.0"
tokio = { version = "1.10.1", features = ["full"] }

[target.'cfg(unix)'.dependencies]
nix = "0.22.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["commapi", "knownfolders", "mswsock", "objbase", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"] }
