# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webstorage"
<<<<<<< HEAD
version = "0.139.0"
=======
version = "0.140.0"
>>>>>>> 04c0a4cbf (1.42.2 (#23314))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of WebStorage API for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_web.workspace = true
rusqlite.workspace = true
serde.workspace = true
