# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webstorage"
<<<<<<< HEAD
version = "0.141.0"
=======
version = "0.142.0"
>>>>>>> 7cb23c5e3 (1.42.4 (#23390))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of WebStorage API for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_web.workspace = true
rusqlite.workspace = true
serde.workspace = true
