# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webstorage"
version = "0.68.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of WebStorage API for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.155.0", path = "../../core" }
deno_web = { version = "0.104.0", path = "../web" }
rusqlite = { version = "0.28.0", features = ["unlock_notify", "bundled"] }
serde = { version = "1.0.136", features = ["derive"] }
