# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webstorage"
version = "0.84.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of WebStorage API for Deno"

[features]
will_take_snapshot = ["deno_core/will_take_snapshot"]
will_load_snapshot = ["deno_core/will_load_snapshot"]

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_web.workspace = true
rusqlite.workspace = true
serde.workspace = true
