# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_runtime_ops"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Ops for the deno_runtime crate"

[lib]
path = "lib.rs"

[dependencies]
async-trait.workspace = true
deno_core.workspace = true
deno_fetch.workspace = true
deno_http.workspace = true
deno_io.workspace = true
deno_net.workspace = true
deno_node.workspace = true
deno_web.workspace = true
deno_websocket.workspace = true
deno_webstorage.workspace = true
encoding_rs.workspace = true
hyper.workspace = true
libc.workspace = true
log.workspace = true
netif = "0.1.6"
notify.workspace = true
serde.workspace = true
signal-hook-registry = "1.4.0"
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
fwdansi.workspace = true
winapi = { workspace = true, features = ["commapi", "knownfolders", "mswsock", "objbase", "psapi", "shlobj", "tlhelp32", "winbase", "winerror", "winuser", "winsock2"] }
ntapi = "0.4.0"

[target.'cfg(unix)'.dependencies]
nix.workspace = true
