# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "serde_v8"
<<<<<<< HEAD
version = "0.93.0"
=======
version = "0.94.0"
>>>>>>> d5f52ef7a (1.33.1 (#18895))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Rust to V8 serialization and deserialization"

[lib]
path = "lib.rs"

[dependencies]
bytes.workspace = true
derive_more = "0.99.17"
num-bigint.workspace = true
serde.workspace = true
serde_bytes.workspace = true
smallvec = { workspace = true, features = ["union"] }
thiserror.workspace = true
v8.workspace = true

[dev-dependencies]
bencher.workspace = true
serde_json.workspace = true

[[example]]
name = "basic"

[[bench]]
name = "de"
harness = false

[[bench]]
name = "ser"
harness = false
