# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_bench_util"
version = "0.67.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = true
readme = "README.md"
repository.workspace = true
description = "Bench and profiling utilities for deno crates"

[lib]
path = "lib.rs"

[dependencies]
bencher = "0.1"
deno_core = { version = "0.155.0", path = "../core" }
once_cell = "1.10.0"
tokio = { version = "1.21", features = ["full"] }

[[bench]]
name = "op_baseline"
harness = false

[[bench]]
name = "utf8"
harness = false
