# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_bench_util"
<<<<<<< HEAD
version = "0.146.0"
=======
version = "0.147.0"
>>>>>>> 7df3d5aee (1.43.6 (#23932))
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = true
readme = "README.md"
repository.workspace = true
description = "Bench and profiling utilities for deno crates"

[lib]
path = "lib.rs"

[dependencies]
bencher.workspace = true
deno_core.workspace = true
tokio.workspace = true

[[bench]]
name = "utf8"
harness = false
