# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_canvas"
<<<<<<< HEAD
version = "0.15.0"
=======
version = "0.16.0"
>>>>>>> 7cb23c5e3 (1.42.4 (#23390))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "OffscreenCanvas implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_webgpu.workspace = true
image = { version = "0.24.7", default-features = false, features = ["png"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
