# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_canvas"
<<<<<<< HEAD
version = "0.3.0"
=======
version = "0.4.0"
>>>>>>> 9a55a72cf (1.40.2 (#22131))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "OffscreenCanvas implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_webgpu.workspace = true
image = { version = "0.24.7", default-features = false, features = ["png"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
