# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_canvas"
version = "0.1.0"
authors = ["the Deno authors"]
edition.workspace = true
license = "MIT"
readme = "README.md"
description = "OffscreenCanvas implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_webgpu.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
