# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webidl"
<<<<<<< HEAD
version = "0.144.0"
=======
version = "0.145.0"
>>>>>>> 04c0a4cbf (1.42.2 (#23314))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "WebIDL implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true

[dev-dependencies]
deno_bench_util.workspace = true

[[bench]]
name = "dict"
harness = false
