# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webgpu"
version = "0.33.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/gfx-rs/wgpu"
description = "WebGPU implementation for Deno"

[dependencies]
deno_core = { version = "0.114.0", path = "../../core" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.10", features = ["full"] }
wgpu-core = { git = "https://github.com/gfx-rs/wgpu", rev = "58771175290bca7b9db546b3451d32fab2dc5d7b", features = ["trace", "replay", "serde"] }
wgpu-types = { git = "https://github.com/gfx-rs/wgpu", rev = "58771175290bca7b9db546b3451d32fab2dc5d7b", features = ["trace", "replay", "serde"] }
