# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webgpu"
version = "0.35.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/gfx-rs/wgpu"
description = "WebGPU implementation for Deno"

[dependencies]
deno_core = { version = "0.116.0", path = "../../core" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.10", features = ["full"] }
wgpu-core = { git = "https://github.com/kvark/wgpu", rev = "c4aa3eaed020a640fec06b48f0a5ea93490d41bb", features = ["trace", "replay", "serde"] }
wgpu-types = { git = "https://github.com/kvark/wgpu", rev = "c4aa3eaed020a640fec06b48f0a5ea93490d41bb", features = ["trace", "replay", "serde"] }
