# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_ffi"
version = "0.1.0"
edition = "2018"
description = "Dynamic library ffi for deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.92.0", path = "../../core" }
serde = { version = "1.0.125", features = ["derive"] }
dlopen = "0.1.8"
libffi = "1.0.1"
