# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "test_ffi"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
pretty_assertions = "1.2.1"
test_util = { path = "../test_util" }
