# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_net"
version = "0.100.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Networking for Deno"

[lib]
path = "lib.rs"

[features]
# Enable to exclude JS sources from the binary (e.g. if they are already snapshotted).
exclude_js_sources = []
# Enable to override `exclude_js_sources` (e.g. for snapshot creation in `build.rs`).
force_include_js_sources = []

[dev-dependencies]
deno_core = { workspace = true, features = ["force_include_js_sources"] }

[dependencies]
deno_core.workspace = true
deno_tls.workspace = true
# Pinning to 0.5.1, because 0.5.2 breaks "cargo publish"
# https://github.com/bluejekyll/enum-as-inner/pull/91
enum-as-inner = "=0.5.1"
log.workspace = true
pin-project.workspace = true
serde.workspace = true
socket2.workspace = true
tokio.workspace = true
trust-dns-proto = "0.22"
trust-dns-resolver = { version = "0.22", features = ["tokio-runtime", "serde-config"] }
