# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_tls"
<<<<<<< HEAD
version = "0.117.0"
=======
version = "0.118.0"
>>>>>>> aa23ccd1a (1.39.3 (#21913))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "TLS for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_native_certs = "0.2.0"
once_cell.workspace = true
rustls = { workspace = true, features = ["dangerous_configuration"] }
rustls-pemfile.workspace = true
rustls-webpki.workspace = true
serde.workspace = true
webpki-roots.workspace = true
