# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_tls"
version = "0.60.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "TLS for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.155.0", path = "../../core" }
once_cell = "1.10.0"
rustls = { version = "0.20.5", features = ["dangerous_configuration"] }
rustls-native-certs = "0.6.2"
rustls-pemfile = "1.0.0"
serde = { version = "1.0.136", features = ["derive"] }
webpki = "0.22"
webpki-roots = "0.22"
