# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_tls"
<<<<<<< HEAD
version = "0.139.0"
=======
version = "0.140.0"
>>>>>>> 7df3d5aee (1.43.6 (#23932))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "TLS for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_native_certs = "0.2.0"
rustls = { workspace = true, features = ["dangerous_configuration"] }
rustls-pemfile.workspace = true
rustls-tokio-stream.workspace = true
rustls-webpki.workspace = true
serde.workspace = true
tokio.workspace = true
webpki-roots.workspace = true
