# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_ops"
<<<<<<< HEAD
version = "0.68.0"
=======
version = "0.69.0"
>>>>>>> ef24d1a0b (1.34.3 (#19525))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Proc macro for writing Deno Ops"

[lib]
path = "./lib.rs"
proc-macro = true

[dependencies]
lazy-regex.workspace = true
once_cell.workspace = true
pmutil = "0.5.3"
proc-macro-crate = "1.1.3"
proc-macro2.workspace = true
quote.workspace = true
regex.workspace = true
syn.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
prettyplease = "0.1.21"
testing_macros = "0.2.7"
trybuild = "1.0.71"
