# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_web"
version = "0.139.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Collection of Web APIs"

[lib]
path = "lib.rs"

[features]
# Enable to exclude JS sources from the binary (e.g. if they are already snapshotted).
exclude_js_sources = []
# Enable to override `exclude_js_sources` (e.g. for snapshot creation in `build.rs`).
force_include_js_sources = []

[dependencies]
async-trait.workspace = true
base64-simd = "0.8"
deno_core.workspace = true
encoding_rs.workspace = true
flate2.workspace = true
serde = "1.0.149"
tokio.workspace = true
uuid = { workspace = true, features = ["serde"] }
windows-sys.workspace = true

[dev-dependencies]
deno_bench_util.workspace = true
deno_console.workspace = true
deno_url.workspace = true
deno_webidl.workspace = true

[[bench]]
name = "encoding"
harness = false

[[bench]]
name = "timers_ops"
harness = false
