# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_web"
<<<<<<< HEAD
version = "0.164.0"
=======
version = "0.165.0"
>>>>>>> b003ecec6 (1.40.1 (#22103))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Collection of Web APIs"

[lib]
path = "lib.rs"

[dependencies]
async-trait.workspace = true
base64-simd = "0.8"
bytes.workspace = true
deno_core.workspace = true
encoding_rs.workspace = true
flate2 = { workspace = true, features = ["default"] }
futures.workspace = true
serde = "1.0.149"
tokio.workspace = true
uuid = { workspace = true, features = ["serde"] }
windows-sys.workspace = true

[dev-dependencies]
deno_bench_util.workspace = true
deno_console.workspace = true
deno_url.workspace = true
deno_webidl.workspace = true

[[bench]]
name = "encoding"
harness = false

[[bench]]
name = "timers_ops"
harness = false
