# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_cron"
<<<<<<< HEAD
version = "0.32.0"
=======
version = "0.33.0"
>>>>>>> 7df3d5aee (1.43.6 (#23932))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of the Deno cron API"

[lib]
path = "lib.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
deno_core.workspace = true
saffron.workspace = true
tokio.workspace = true
