# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_cron"
<<<<<<< HEAD
version = "0.24.0"
=======
version = "0.25.0"
>>>>>>> 04c0a4cbf (1.42.2 (#23314))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of the Deno cron API"

[lib]
path = "lib.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
deno_core.workspace = true
deno_unsync = "0.1.1"
saffron.workspace = true
tokio.workspace = true
