name: Benchmark updating

on:
  push:
    branch:
      - master

jobs:
  update_benchmark:
    name: Update benchmarks
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v1
        with:
          submodules: true

      # Setup compilers
      - name: Setup rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: "1.37.0"
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "2.7.16"
          architecture: x64
      - name: Check versions
        run: |
          python --version
          rustc --version
          cargo --version

      # Setup
      - name: Run setup script
        run: ./tools/setup.py

      # Start sscache
      - name: Start sccache
        run: "`pwd`/prebuilt/linux64/sccache --start-server"

      # Building
      - name: Run build script
        env:
          DENO_BUILD_MODE: release
        run: |
          cargo build --release --locked --all-targets
      
      # Run benchmarks
      - name: Run benchmarks
        run: |
          ./tools/benchmark.py target/release

      - name: Copy benchmarks
        run: cp -r website/* gh-pages/

      # Upload benchmarks
      - name: Upload benchmarks as artifact
        uses: actions/upload-artifact@master
        with:
          name: benchmarks
          path: gh-pages

      # Push to pages
      #- name: Push to pages (macos)
      #  run: |
      #    cd gh-pages
      #    git add .
      #    git commit --message "Update benchmarks"
      #    git push origin gh-pages
