name: ci

on: [push, pull_request]

jobs:
  build:
    name: build / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-18.04
          - windows-2019
          - macos-10.15

    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: full
      CARGO_TERM_COLOR: always

    outputs:
      ref: ${{ steps.release.outputs.ref }}

    steps:
      - name: Configure Git
        run: git config --global core.symlinks true

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          submodules: true

      - name: Get Commit Hash
        id: release
        run: echo "::set-output name=ref::$(git rev-parse HEAD)"

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          default: true
          override: true
          toolchain: 1.50.0

      - name: Configure Canary
        shell: bash
        run: echo 'DENO_CANARY=true' >> $GITHUB_ENV

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --locked --all-targets --release

      - name: Zip Linux Build
        if: runner.os == 'Linux'
        working-directory: target/release
        run: |
          zip -r deno-x86_64-unknown-linux-gnu.zip deno
          zip -r denort-x86_64-unknown-linux-gnu.zip denort

      - name: Zip MacOS Build
        if: runner.os == 'macOS'
        working-directory: target/release
        run: |
          zip -r deno-x86_64-apple-darwin.zip deno
          zip -r denort-x86_64-apple-darwin.zip denort

      - name: Zip Windows Build
        if: runner.os == 'Windows'
        working-directory: target/release
        run: |
          Compress-Archive -CompressionLevel Optimal -Force -Path deno.exe -DestinationPath deno-x86_64-pc-windows-msvc.zip
          Compress-Archive -CompressionLevel Optimal -Force -Path denort.exe -DestinationPath denort-x86_64-pc-windows-msvc.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: canary
          path: |
            target/release/deno-x86_64-unknown-linux-gnu.zip
            target/release/deno-x86_64-pc-windows-msvc.zip
            target/release/deno-x86_64-apple-darwin.zip
            target/release/denort-x86_64-unknown-linux-gnu.zip
            target/release/denort-x86_64-pc-windows-msvc.zip
            target/release/denort-x86_64-apple-darwin.zip
          retention-days: 7

  test:
    name: test / ${{ matrix.kind }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        kind: ["debug", "release"]
        # TODO(ry) Ideally we would use ubuntu-latest-xl for test/debug/*,
        # but there are race conditions in our test we are working around by
        # using the slower runner.

        # Warning: Do not upgrade test/release/* to newer version of ubuntu
        # runners. We need to link against older version of glibc in order to
        # run on older systems. glibc in 20.04 is not compatible with 18.04.
        # See #9484.
        os:
          - ubuntu-18.04
          - windows-2019
          - macos-10.15
        exclude:
          - kind: debug
            os: windows-2019
          - kind: debug
            os: macos-10.15

    outputs:
      ref: ${{ steps.release.outputs.ref }}

    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: full
      CARGO_TERM_COLOR: always

    steps:
      - name: Configure Git
        run: git config --global core.symlinks true

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          submodules: true

      - name: Get Release Tag
        id: release
        run: echo "::set-output name=ref::$(echo ${GITHUB_REF#refs/*/})"

      - name: Create Source Tarball
        if: runner.os == 'Linux'
        run: |
          mkdir -p target/release
          tar --exclude=.cargo_home --exclude=".git*" --exclude=target --exclude=third_party/prebuilt -czf target/release/deno_src.tar.gz -C .. deno

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          default: true
          override: true
          toolchain: 1.50.0

      - name: Setup Deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.7.2
          echo "$HOME/.deno/bin" >> $${{ runner.os == 'Windows' && 'env:' || '' }}GITHUB_PATH

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: x64

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true

      - name: Remove Unused Python
        if: runner.os == 'Windows'
        run: |-
          $env:PATH -split ";" |
            Where-Object { Test-Path "$_\python.exe" } |
            Select-Object -Skip 1 |
            ForEach-Object { Move-Item "$_" "$_.disabled" }

      - name: Log versions
        run: |
          node --version
          python --version
          rustc --version
          cargo --version
          deno --version

      - name: Build (${{ matrix.kind }})
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --locked --all-targets ${{ matrix.kind == 'release' && '--release -vv' || '' }}

      - name: Test release
        if: matrix.kind == 'release'
        run: cargo test --release --locked --all-targets

      - name: Test debug
        if: matrix.kind == 'debug'
        run: |
          cargo test --locked --doc
          cargo test --locked --all-targets

      - name: Configure hosts file for WPT (unix)
        if: runner.os != 'Windows'
        working-directory: test_util/wpt/
        run: ./wpt make-hosts-file | sudo tee -a /etc/hosts

      - name: Configure hosts file for WPT (windows)
        if: runner.os == 'Windows'
        working-directory: test_util/wpt/
        run: python wpt make-hosts-file | Out-File $env:SystemRoot\System32\drivers\etc\hosts -Encoding ascii -Append

      - name: Run web platform tests (${{ matrix.kind }})
        run: |
          deno run --unstable --allow-write --allow-read --allow-net --allow-env --allow-run ./tools/wpt.ts setup
          deno run --unstable --allow-write --allow-read --allow-net --allow-env --allow-run ./tools/wpt.ts run --quiet ${{ matrix.kind == 'release' && '--release' || '' }}

      - name: Zip Linux Build
        if: matrix.kind == 'release' && runner.os == 'Linux'
        working-directory: target/release
        run: |
          zip -r deno-x86_64-unknown-linux-gnu.zip deno
          zip -r denort-x86_64-unknown-linux-gnu.zip denort
          ./deno types > lib.deno.d.ts

      - name: Zip MacOS Build
        if: matrix.kind == 'release' && runner.os == 'macOS'
        working-directory: target/release
        run: |
          zip -r deno-x86_64-apple-darwin.zip deno
          zip -r denort-x86_64-apple-darwin.zip denort

      - name: Zip Windows Build
        if: matrix.kind == 'release' && runner.os == 'Windows'
        working-directory: target/release
        run: |
          Compress-Archive -CompressionLevel Optimal -Force -Path deno.exe -DestinationPath deno-x86_64-pc-windows-msvc.zip
          Compress-Archive -CompressionLevel Optimal -Force -Path denort.exe -DestinationPath denort-x86_64-pc-windows-msvc.zip

      - name: Upload Artifacts
        if: matrix.kind == 'release'
        uses: actions/upload-artifact@v2
        with:
          name: stable
          path: |
            target/release/deno-x86_64-unknown-linux-gnu.zip
            target/release/deno-x86_64-pc-windows-msvc.zip
            target/release/deno-x86_64-apple-darwin.zip
            target/release/denort-x86_64-unknown-linux-gnu.zip
            target/release/denort-x86_64-pc-windows-msvc.zip
            target/release/denort-x86_64-apple-darwin.zip
            target/release/deno_src.tar.gz
            target/release/lib.deno.d.ts
          retention-days: 7

  lint:
    # TODO(ry) Ideally we could use ubuntu-latest-xl for lint but there's
    # a bug with dprint that is preventing this from running.
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Configure Git
        run: git config --global core.symlinks true

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.50.0
          default: true
          override: true
          components: rustfmt, clippy

      - name: Setup Deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.7.2
          echo "$HOME/.deno/bin" >> $${{ runner.os == 'Windows' && 'env:' || '' }}GITHUB_PATH

      - name: Log versions
        run: |
          rustc --version
          cargo --version
          deno --version

      - name: test_format.js
        run: deno run --unstable --allow-write --allow-read --allow-run ./tools/format.js --check

      - name: lint.js
        run: deno run --unstable --allow-write --allow-read --allow-run ./tools/lint.js

  bench:
    runs-on: ${{ github.repository == 'denoland/deno' && 'ubuntu-latest-xl' || 'ubuntu-latest' }}
    timeout-minutes: 60

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Configure Git
        run: git config --global core.symlinks true

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          default: true
          override: true
          toolchain: 1.50.0

      - name: Setup Deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.7.2
          echo "$HOME/.deno/bin" >> $${{ runner.os == 'Windows' && 'env:' || '' }}GITHUB_PATH

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: x64

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true

      - name: Log versions
        run: |
          node --version
          python --version
          rustc --version
          cargo --version
          deno --version

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --locked --all-targets --release -vv

      - name: Configure hosts file for WPT
        if: runner.os != 'Windows'
        working-directory: test_util/wpt/
        run: ./wpt make-hosts-file | sudo tee -a /etc/hosts

      - name: Run Benchmarks
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: bench

      - name: Post Benchmarks
        if: github.repository == 'denoland/deno' && github.ref == 'refs/heads/main'
        env:
          DENOBOT_PAT: ${{ secrets.DENOBOT_PAT }}
        run: |
          git clone --depth 1 -b gh-pages https://${DENOBOT_PAT}@github.com/denoland/benchmark_data.git gh-pages
          deno run --unstable -A ./tools/build_benchmark_jsons.js --release
          cd gh-pages
          git config user.email "propelml@gmail.com"
          git config user.name "denobot"
          git add .
          git commit --message "Update benchmarks"
          git push origin gh-pages

      - name: Worker info
        run: |
          cat /proc/cpuinfo
          cat /proc/meminfo

  release-canary:
    name: release / canary
    if: github.repository == 'denoland/deno' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: canary
          path: ./canary

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: denoland
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Upload Builds
        run: |
          gsutil cp ./canary/*.zip gs://dl.deno.land/canary/${{ needs.build.outputs.ref }}/
          echo -n ${{ needs.build.outputs.ref }} > canary-latest.txt
          gsutil cp canary-latest.txt gs://dl.deno.land/canary-latest.txt

  release-stable:
    name: release / stable
    if: github.repository == 'denoland/deno' && startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: stable
          path: ./stable

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: denoland
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Upload Builds
        run: |
          gsutil cp ./stable/*.zip gs://dl.deno.land/release/${{ needs.test.outputs.ref }}/
          echo -n ${{ needs.test.outputs.ref }} > release-latest.txt
          gsutil cp release-latest.txt gs://dl.deno.land/release-latest.txt

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            stable/deno-x86_64-unknown-linux-gnu.zip
            stable/deno-x86_64-pc-windows-msvc.zip
            stable/deno-x86_64-apple-darwin.zip
            stable/lib.deno.d.ts
            stable/deno_src.tar.gz
          draft: true
