name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest-xl
    steps:
      - uses: actions/checkout@v2

      - name: deno
        run: |
          chmod +x fast.sh
          ./fast.sh
