name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.variant }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            variant: 1
          - os: ubuntu-18.04
            variant: 2
          - os: ubuntu-18.04
            variant: 3

      fail-fast: false

    env:
      RUST_BACKTRACE: full
      CARGO_TERM_COLOR: always

    steps:
      - name: Test
        run: echo Cargo.toml-${{ matrix.variant }}

      - name: Configure git
        run: git config --global core.symlinks true

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # Use depth > 1, because sometimes we need to rebuild main and if
          # other commits have landed it will become impossible to rebuild if
          # the checkout is too shallow.
          fetch-depth: 5
          submodules: recursive

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.51.0

      - name: Install Deno
        run: |-
          curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.7.2
          echo "$HOME/.deno/bin" >> $GITHUB_PATH

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: x64

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true

      - name: Butcher Cargo.toml
        run: cat Cargo.toml-${{ matrix.variant }} >>Cargo.toml

      - name: Clean build
        run: |
          cargo build --release --locked --all-targets -vv
          cargo test --no-run --release --locked --all-targets -vv

      - name: Incremental build
        run: |
          echo "// hi" >> runtime/js/40_http.js
          cargo build --release --locked --all-targets -vv
          cargo test --no-run --release --locked --all-targets -vv

      - name: Print sizes
        run: |
          du -h -t100m target/
          du -ah target/release/deno
          du -ah target/release/denort
